materialedhsubexpapi:
# Listner details
  http:
    path: "/api/v1/dev/MaterialEDHSubscriber_vs0/MaterialEDHSubscriber_vs0_http1"

# API Autodiscovery details
  api:
    autodiscovery:
      id: "15559932"
      
# Web Service Consumer details      
  web:
    service: "#[vars.wsdlService]"
    port: "#[vars.wsdlPort]"
    address: "#[vars.wsdlAddress]"
    wsdl:
      name: "#[vars.wsdlName]"
# WSDL details for web service consumer 
  wsdl:
    target:
      name: "http://edhws-test.amgen.com:80/Amgen.ERP.Material.Subscriber/MaterialEDHSubscriber.asmx?wsdl"
      port: "MaterialClientV1_0SOAP1"
      service: "SubscriberService"
      address: "http://edhws-test.amgen.com/Amgen.ERP.Material.Subscriber/MaterialEDHSubscriber.asmx" 
    source:
      name: "api/MaterialEDHService.wsdl"
      port: "MaterialEDHSubscriber_vs0_http1"
      service: "MaterialEDHSubscriber_vs0"       
#Logging details          
  main:
    organizationId: "amgen"
    domainName: "gbs"
    logSuccessStatus: "Success"
    logInProcessStatus: "InProgress"
    logErrorStatus: "Error"
    integrationId: "INT019"
    integrationName: "edhmaterial" 
    processType: "materialEdhSubExpApi"
    sourceSystemId: "sap"
    destinationSystemId: "edh"